language: php

php:
    - 5.5

env:
    - WP_VERSION=3.5.2 WP_MULTISITE=0

before_install:
    - set -ex
    # composer install
    # set up wp-cli
    - export VERSION="dev-master"
    - curl http://wp-cli.org/installer.sh | bash
    - cd $HOME/.composer
    - php composer.phar config repositories.theme_test vcs $TRAVIS_BUILD_DIR
    - php composer.phar update

before_script:
    # set up WP install
    - WP_CORE_DIR=/tmp/wordpress/
    - mkdir -p $WP_CORE_DIR
    # set up database
    - mysql -e 'CREATE DATABASE wordpress_test;' -uroot
    - $HOME/.composer/bin/wp core download --version=$WP_VERSION --path=$WP_CORE_DIR
    - $HOME/.composer/bin/wp core config --dbname=wordpress_test --dbuser=root  --path=$WP_CORE_DIR
    - $HOME/.composer/bin/wp core install --url=http://localhost --title="WP" --admin_name=test --admin_email=test@example.org --admin_password=test --path=$WP_CORE_DIR
    # $HOME/.composer/bin/wp theme-test install --menus --path=$WP_CORE_DIR

script: $HOME/.composer/bin/wp help
