language: php

php:
    - 5.3
    - 5.5

env:
    - WP_VERSION=master WP_MULTISITE=0
    - WP_VERSION=3.5.2 WP_MULTISITE=0

before_install:
    - git submodule update --init --recursive

before_script:
    # set up database
    - mysql -e 'CREATE DATABASE wordpress_test;' -uroot
    - set -ex
    - composer install --dev --no-interaction --prefer-source
    - composer require wp-cli/wp-cli=dev-master --no-interaction --prefer-source
    - composer require d11wtq/boris=@stable --no-interaction --prefer-source
    - composer require pixline/wp-cli-theme-test-command=dev-master --no-interaction --prefer-source

script: phpunit
