language: php

php:
    - 5.5

env:
    - WP_VERSION=3.5.2 WP_MULTISITE=0

before_install:
    - set -ex
    # - composer install
    # set up wp-cli
    - export VERSION="dev-master"
    - export WP_CORE_DIR="/tmp/wordpress"
    - curl http://wp-cli.org/installer.sh | bash
    - cd $HOME/.wp-cli
    - php composer.phar install --dev --no-interaction --prefer-source
    - php composer.phar config repositories.theme_test vcs $TRAVIS_BUILD_DIR
    - php composer.phar update --dev --no-interaction --prefer-source
    # - php composer.phar require pixline/wp-cli-theme-test-command=dev-$TRAVIS_BRANCH

before_script:
    - $HOME/.wp-cli/bin/wp --info
    - $HOME/.wp-cli/bin/wp core download --version=$WP_VERSION --path=$WP_CORE_DIR
    - $HOME/.wp-cli/bin/wp core config --dbname=wordpress_test --dbuser=root  --path=$WP_CORE_DIR
    - $HOME/.wp-cli/bin/wp core install --url=http://localhost --title="WP" --admin_name=test --admin_email=test@example.org --admin_password=test --path=$WP_CORE_DIR
    - $HOME/.wp-cli/bin/wp theme-test install --menus --path=$WP_CORE_DIR

script: exit 0
