language: php

php:
    - 5.5

env:
    - WP_VERSION=master WP_MULTISITE=0

before_install:
    # set up database
    - mysql -e 'CREATE DATABASE wordpress_test;' -uroot

before_script:
    - set -ex
    - composer install --dev --no-interaction --prefer-source
    - composer config repositories.wp-cli vcs https://github.com/wp-cli/wp-cli
    - composer require wp-cli/wp-cli=dev-master --no-interaction --prefer-source
    - cat /home/travis/.composer/composer.json

script: /home/travis/.composer/bin/wp
