language: php

php:
    - 5.5

env:
    - WP_VERSION=3.5.2 WP_MULTISITE=0

before_install:
    - set -ex
    # - composer install
    # set up wp-cli
    - export VERSION="dev-master"
    - export WP_CORE_DIR="/tmp/wordpress"
    - mysql -e 'CREATE DATABASE wordpress_test;' -uroot
    # - php composer.phar config repositories.theme_test vcs $TRAVIS_BUILD_DIR
    # - php composer.phar update --dev --no-interaction --prefer-source
    # - php composer.phar require pixline/wp-cli-theme-test-command=dev-$TRAVIS_BRANCH

before_script:
    - cd $TRAVIS_BUILD_DIR
    - composer install --dev --no-interaction --prefer-source
    - export PATH="$TRAVIS_BUILD_DIR/vendor/bin/:$PATH"
    - cd $WP_CORE_DIR
    - wp --info
    - wp core download --version=$WP_VERSION
    - wp core config --dbname=wordpress_test --dbuser=root
    - wp core install --url=http://localhost --title="WP" --admin_email=test@example.org --admin_password=test
    - wp theme-test install --menus

script: exit 0
